language: python
notifications:
  email: false
sudo: false
python:
  - 3.4
  - 3.5
  - 3.6 
  - pypy3
matrix:
  include:
    - python: 3.6
      dist: trusty
      sudo: required
      virtualenv:
        system_site_packages: true
      addons:
        apt:
          packages:
            - python-requests
            - python-coverage
            - python-mock

install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  - nosetests --with-coverage
after_success:
  - codecov
