language: python
notifications:
  email: false
sudo: false
python:
  - 3.4
  - 3.5
  - 3.6 
  - pypy3
install:
  - pip install -r requirements.txt
  - pip install codecov
  - python setup.py install
script:
  - coverage run tests/tests.py
after_success:
  - codecov
