site_name: smote_variants

nav:
    - Home: 'index.md'
    - Citation: 'citation.md'
    - User Guide: 
        - Installation: 'installation.md'
        - Implemented techniques: 'implementations.md'
    - About: 
        - 'License': 'license.md'
        - 'Release Notes': 'release-notes.md'
theme: readthedocs
